### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mimipeshy** [e71az/dream-funding#1]
Hi Elias,
You are doing such awesome work with the capstone project :clap:  :clap:  . You are almost done so don't give up yet. Here are a few things you need to check before submitting for review

- [x]  edit your webpacker file to compile: true this will fix your webpacker conflict with Heroku

- [x] Ensure your bootstrap file is working on Heroku, currently it's not. Always use yarn install bootstrap

- [x] Check that you dont have logic on the views

- [x] Update your readme file

That's it :relieved: . Happy coding :computer: 
#team-122-the-manx

**Comment by eliasecasta** [comment]
Thank you very much Peris, applied your suggested changes :)

Long live #team-122-the-manx, WAAAARMMMMMM
